### ISSUE TITLE
Does this have a License

### ISSUE THREAD

**Issue by inorton** [lolp1/Overlay.NET#13]
Hiya,

I've picked this up and have been very impressed with how easy and fast it has been for me. I'd really like to bundle a build of this with one of my open source projects - https://github.com/inorton/EDMCOverlay (my audience are not people who have compilers on hand).  What license should I assume this is for?

Thanks, Ian

**Comment by lolp1** [comment]
In its current form, MIT license applies and for that you have my word. Later versions may be monetized due to the effort that was needed to implement things such as directly using games devices to render directx content via detours etc.

This version is free to drag and drop into your code, while I would prefer credits, even that is not needed. Enjoy.

**Comment by inorton** [comment]
Many thanks 👍 :)
