### ISSUE TITLE
DirectX not drawing on some computers

### ISSUE THREAD

**Issue by njbrown09** [lolp1/Overlay.NET#14]
DirectX overlays arent drawing on some computers

**Comment by lolp1** [comment]
https://github.com/lolp1/Overlay.NET/issues/12

Review comments here (a fix is provided). I will close the close the issue once its fixed in the lib its self. A little busy so would love for some one to make pull request with the mentioned changes and a basic test, but short of that or getting spare time and motivation that is looking a week or two down the road.

**Comment by lolp1** [comment]
This was recently fixed.
