### ISSUE TITLE
WpfOverlay not rendering in loop?

### ISSUE THREAD

**Issue by bestplay9384** [lolp1/Overlay.NET#16]
Hey,

I'm not sure, probably i'm doing something wrong, but in your WPF Demo app overriden function Draw on OverlayWindow is being executed only once for me. And on initialize everything is flickering until i touch something from overlay with my mouse. Is it normal behaviour? What i would like to do is to draw and clear the WPF Overlay in while(true) loop. Thanks for help in advance :)

**Comment by lolp1** [comment]
Any chance you have xbox DVR enabled?

**Comment by ThorConzales** [comment]
I have the same problem and I did disable Xbox DVR but still have the same issue. I assume the OnDraw event should be called continuously and text you would like to update should be updated inside that method but currently it is only called few times in the beginning and then it stops. If I'm wrong then what is the correct way of updating a text on the screen?

**Comment by ThorConzales** [comment]
It seems to be WPF specific problem why it is not rendering in loop. I did recreate my own simple WPF project with transparent window and there everything seems to work. As for the flickering then it is caused by getting invalid signal whether the window is focused or not. I do recommend trying it out in release build and seeing if it is still flickering.

**Comment by lolp1** [comment]
Fixing this + events soon.
