### ISSUE TITLE
Add Shared process

### ISSUE THREAD

**Issue by Traderain** [lolp1/Overlay.NET#2]
So we can modify the ui of games and such

**Comment by lolp1** [comment]
@Traderain 
Hi,

Since time is limited, I am considering making this feature very user-friendly and offer the extra features library as a small license fee. 

At the very least, soon there will be support to detour endscene or present, but the rest of the work in this version might be left up to the user, this I have not decided yet.

Let me know specifically what features you want from this and why if you would like to give me more insight on what people using the library want.

**Comment by Traderain** [comment]
@lolp1 I would gladly pay for it. I am currently making an program wich has an overlay feature for source engine and goldsource engine games and it would be extremely usefull if I could use the same directx device the game is using and draw into the game's ui (I hope that makes sense).

**Comment by lolp1** [comment]
@Traderain Please contact me via email (JacobKemple@outlook.com) or skype (same as my email) to talk further to see if I can meet your needs in a way that makes sense for us both.

**Comment by Traderain** [comment]
Contacted

**Comment by lolp1** [comment]
Please re-send the email to JacobKemple@outlook.com and include your GitHub name, thanks!
